# Generated by Django 6.0 on 2025-12-23 09:49

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_streamfieldpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedStreamFieldPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('quote', 1), ('hero', 5), ('links', 8), ('items', 10), ('image', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 2), ('subtitle', 3), ('image', 4)]], {}), 6: ('wagtail.blocks.URLBlock', (), {'required': True}), 7: ('wagtail.blocks.StructBlock', [[('title', 2), ('url', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Item'}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
            ],
            options={
                'verbose_name': 'Advanced StreamField Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
