# Generated by Django 6.0 on 2025-12-23 10:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_advancedstreamfieldpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedstreamfieldpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('quote', 1), ('hero', 5), ('links', 8), ('items', 10), ('image', 11), ('section', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 2), ('subtitle', 3), ('image', 4)]], {}), 6: ('wagtail.blocks.URLBlock', (), {'required': True}), 7: ('wagtail.blocks.StructBlock', [[('title', 2), ('url', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Item'}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 12: ('wagtail.blocks.TextBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 2), ('description', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 2), ('cards', 14)]], {})}),
        ),
    ]
