# Generated by Django 6.0 on 2025-12-23 14:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_advancedstreamfieldpage_body'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBlockTypesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('char', 0), ('text', 1), ('email', 2), ('url', 3), ('regex', 4), ('integer', 5), ('float', 6), ('decimal', 7), ('date', 8), ('time', 9), ('datetime', 10), ('richtext', 11), ('rawhtml', 12), ('blockquote', 13), ('boolean', 14), ('choice', 15), ('multiple_choice', 16), ('image', 17), ('document', 18), ('page', 19), ('snippet', 20), ('embed', 21), ('struct', 25), ('list', 27), ('nested_stream', 30)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Char Block'}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Text Block'}), 2: ('wagtail.blocks.EmailBlock', (), {'label': 'Email Block'}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'URL Block'}), 4: ('wagtail.blocks.RegexBlock', (), {'label': 'Regex Block (3 uppercase)', 'regex': '^[A-Z]{3}$'}), 5: ('wagtail.blocks.IntegerBlock', (), {'label': 'Integer Block'}), 6: ('wagtail.blocks.FloatBlock', (), {'label': 'Float Block'}), 7: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'label': 'Decimal Block'}), 8: ('wagtail.blocks.DateBlock', (), {'label': 'Date Block'}), 9: ('wagtail.blocks.TimeBlock', (), {'label': 'Time Block'}), 10: ('wagtail.blocks.DateTimeBlock', (), {'label': 'DateTime Block'}), 11: ('wagtail.blocks.RichTextBlock', (), {'label': 'Rich Text Block'}), 12: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'Raw HTML Block'}), 13: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Block Quote'}), 14: ('wagtail.blocks.BooleanBlock', (), {'label': 'Boolean Block', 'required': False}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], 'label': 'Choice Block'}), 16: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('red', 'Red'), ('green', 'Green'), ('blue', 'Blue')], 'label': 'Multiple Choice Block'}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image Block'}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document Block'}), 19: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page Block'}), 20: ('wagtail.snippets.blocks.SnippetChooserBlock', ('testapp.TestSnippet',), {'label': 'Snippet Block'}), 21: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Embed Block'}), 22: ('wagtail.blocks.CharBlock', (), {'required': True}), 23: ('wagtail.blocks.CharBlock', (), {'required': False}), 24: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 25: ('wagtail.blocks.StructBlock', [[('title', 22), ('subtitle', 23), ('image', 24)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'label': 'Item'}), 27: ('wagtail.blocks.ListBlock', (26,), {'label': 'List Block'}), 28: ('wagtail.blocks.CharBlock', (), {}), 29: ('wagtail.blocks.BlockQuoteBlock', (), {}), 30: ('wagtail.blocks.StreamBlock', [[('text', 28), ('quote', 29)]], {'label': 'Nested Stream Block'})})),
            ],
            options={
                'verbose_name': 'All Block Types Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
